[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "qubit_control_reinforcement_learning"
authors = [{name = "Dimitris Koutromanos", email = "dkoutromanos@upatras.gr"}]
dynamic = ["version", "description"]
